package constants

// HTTP Constants
// HTTP Status
val RES_STATUS_OK = 200
val RES_STATUS_CREATED = 201
val RES_STATUS_NOT_FOUND = 404
val RES_STATUS_BAD_REQUEST = 400
val RES_STATUS_INTERNAL_ERROR = 500

// HTTP Headers
val RES_HEADER_NAME_CONTENT_TYPE = "Content-type"
val RES_HEADER_CONTENT_TYPE_APP_JSON = "application/json"